account/urls.py
from django.urls import path
from . import views
app_name = 'account'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('detail/<str:username>/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_views

app_name = 'api'

urlpatterns = [
    path('movies/', views.MovieList.as_view()),
    # TODO: make Score API URL
    path('movies/<int:movie_id>/comments/', views.comment),
    path('account/login/', views.login),
    path('movies/<int:movie_id>/detail/', views.detail),
    path('movies/<int:movie_id>/like/', views.like_movie),
    path('movies/<int:movie_id>/comments/<int:comment_id>/delete/', views.comment_delete),
    path('account/auth/', auth_views.obtain_auth_token),
    path('movies/<int:movie_id>/score/', views.score),
]

movie/urls.py
from django.urls import path
from . import views
app_name="movie"
urlpatterns = [
    path('', views.index, name="index"),
    path('list/', views.movies, name="movies"),
]

ssafy_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from movie import views
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('movies/', include('movie.urls')),
    path('', TemplateView.as_view(template_name="main.html"), name='root'),
    path('api/v1/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

untitled/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <!-- Load required Bootstrap and BootstrapVue CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <!-- customize css -->
  <link href="{% static 'movie/css/index.css' %}" type="text/css" rel="stylesheet">
  
  <!-- Font -->
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&amp;subset=korean" rel="stylesheet">
  
  <title>SSAFLIX</title>
</head>
<body>
  {% include "nav.html" %}
  {% block body %}
    
  {% endblock %}

  <!-- Load polyfills to support older browsers -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<div id="footer" class="footer">
    <div class="container-fluid text-center text-md-left footer-container">
        <!-- Grid row -->
        <div class="row mt-5">

            <!-- Grid column -->
            <div class="offset-md-2 col-md-6 mt-md-0 ">

                <!-- Content -->
                <h4 class="text-uppercase">개발왕 김복동 & 오복동</h4>
                <p>
                    술 한잔 마셨읍니다... 평가가 안 좋아도 좋습니다.
                    하지만 SSAFLIX 하나만 기억해주세요<br>
                    진심을 다해 전합니다.<br>
                    사이트가 별로일 수 있읍니다..<br>
                    밤낮으로 고민하고 만들었읍니다...
                    최선을 다했고 열심히 했읍니다...<br>
                    저희의 진심이 느껴지길 바랍니다 고맙습니다...<br>
                    그만큼 사이트가 좋다능..<br>
                </p>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 offset-md-2 mb-md-0 mb-3">

                <!-- Links -->
                <h5 class="text-uppercase">Links</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="#">싸플릭스</a>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center">© 2019 Copyright:
        <a href="#"> TOPSUPDUO.com</a>
    </div>
</div>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&amp;subset=korean" rel="stylesheet">
  <title>SSAFLIX</title>
  <style>
    body {
      margin: 0;
    }
    iframe {
      margin-left: -132px;
      margin-top: -100px;
    }
    .home {
      position: absolute;
      top:0;
      left: 0;
      text-decoration: none;
      color: #FF0000;
      z-index: 77;
      font-size: 40px;
      font-family: 'Do Hyeon', sans-serif;
    }
  </style>
</head>
<body>
    <iframe width="2200" height="1200" src="https://www.youtube.com/embed/UhVjp48U2Oc?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <a class="home" href="http://ssafy-movie-gstjs.c9users.io:8080/movies/">SSAFLIX</a>
    <script>
      setTimeout(function(){
        location.href="http://ssafy-movie-gstjs.c9users.io:8080/movies/"
      },38000)
      
    </script>
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg nav-bar">
  <a class="navbar-brand" id="nav-title" href="{% url 'movie:index' %}">SSAFLIX</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:detail' user.username %}" tabindex="-1" aria-disabled="true">{{ user.username }}</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'account:logout' %}">로그아웃</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link btn btn-danger py-1" href="{% url 'account:login' %}">로그인</a>
      </li>
      <li class="nav-item ml-5 mr-5">
        <a class="nav-link btn btn-danger py-1" href="{% url 'account:signup' %}">회원가입</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>